{"uuid": "09f9737b-de95-4019-8cbd-db0a5453bc0a", "children": ["d8a366bb-3853-4e6c-a193-3c6b786b4c15"], "befores": [{"name": "app_fixture", "status": "broken", "statusDetails": {"message": "_pytest.outcomes.Exit: create app fail: 'device not ready'\n", "trace": "  File \"/Users/gaoxiang/.local/share/virtualenvs/Pytest_Allure_Airtest_Demo-Nvoc_r-F/lib/python3.6/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/gaoxiang/.local/share/virtualenvs/Pytest_Allure_Airtest_Demo-Nvoc_r-F/lib/python3.6/site-packages/_pytest/fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/gaoxiang/.local/share/virtualenvs/Pytest_Allure_Airtest_Demo-Nvoc_r-F/lib/python3.6/site-packages/_pytest/fixtures.py\", line 792, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"/Users/gaoxiang/gaoxiang/Pytest_Allure_Airtest_Demo/cases/conftest.py\", line 78, in app_fixture\n    pytest.exit(\"create app fail: {}\".format(e))\n  File \"/Users/gaoxiang/.local/share/virtualenvs/Pytest_Allure_Airtest_Demo-Nvoc_r-F/lib/python3.6/site-packages/_pytest/outcomes.py\", line 121, in exit\n    raise Exit(msg, returncode)\n"}, "steps": [{"name": "工程初始化和生成APP对象", "status": "broken", "statusDetails": {"message": "_pytest.outcomes.Exit: create app fail: 'device not ready'\n", "trace": "  File \"/Users/gaoxiang/gaoxiang/Pytest_Allure_Airtest_Demo/cases/conftest.py\", line 78, in app_fixture\n    pytest.exit(\"create app fail: {}\".format(e))\n  File \"/Users/gaoxiang/.local/share/virtualenvs/Pytest_Allure_Airtest_Demo-Nvoc_r-F/lib/python3.6/site-packages/_pytest/outcomes.py\", line 121, in exit\n    raise Exit(msg, returncode)\n"}, "steps": [{"name": "初始化驱动", "status": "broken", "statusDetails": {"message": "airtest.core.error.DeviceConnectionError: 'device not ready'\n", "trace": "  File \"/Users/gaoxiang/.local/share/virtualenvs/Pytest_Allure_Airtest_Demo-Nvoc_r-F/lib/python3.6/site-packages/allure_commons/_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"/Users/gaoxiang/gaoxiang/Pytest_Allure_Airtest_Demo/src/common.air/common.py\", line 101, in init_driver\n    self.phone_ip, self.phone_port, self.phone_uuid))\n  File \"/Users/gaoxiang/gaoxiang/Pytest_Allure_Airtest_Demo/src/common.air/common.py\", line 175, in my_retry_connect\n    raise e\n  File \"/Users/gaoxiang/gaoxiang/Pytest_Allure_Airtest_Demo/src/common.air/common.py\", line 170, in my_retry_connect\n    return r(connect_device, uri)\n  File \"/Users/gaoxiang/.local/share/virtualenvs/Pytest_Allure_Airtest_Demo-Nvoc_r-F/lib/python3.6/site-packages/tenacity/__init__.py\", line 358, in call\n    do = self.iter(retry_state=retry_state)\n  File \"/Users/gaoxiang/.local/share/virtualenvs/Pytest_Allure_Airtest_Demo-Nvoc_r-F/lib/python3.6/site-packages/tenacity/__init__.py\", line 331, in iter\n    raise retry_exc.reraise()\n  File \"/Users/gaoxiang/.local/share/virtualenvs/Pytest_Allure_Airtest_Demo-Nvoc_r-F/lib/python3.6/site-packages/tenacity/__init__.py\", line 167, in reraise\n    raise self.last_attempt.result()\n  File \"/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/_base.py\", line 425, in result\n    return self.__get_result()\n  File \"/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/_base.py\", line 384, in __get_result\n    raise self._exception\n  File \"/Users/gaoxiang/.local/share/virtualenvs/Pytest_Allure_Airtest_Demo-Nvoc_r-F/lib/python3.6/site-packages/tenacity/__init__.py\", line 361, in call\n    result = fn(*args, **kwargs)\n  File \"/Users/gaoxiang/.local/share/virtualenvs/Pytest_Allure_Airtest_Demo-Nvoc_r-F/lib/python3.6/site-packages/airtest/core/api.py\", line 63, in connect_device\n    dev = init_device(platform, uuid, **params)\n  File \"/Users/gaoxiang/.local/share/virtualenvs/Pytest_Allure_Airtest_Demo-Nvoc_r-F/lib/python3.6/site-packages/airtest/core/api.py\", line 33, in init_device\n    dev = cls(uuid, **kwargs)\n  File \"/Users/gaoxiang/.local/share/virtualenvs/Pytest_Allure_Airtest_Demo-Nvoc_r-F/lib/python3.6/site-packages/airtest/core/android/android.py\", line 44, in __init__\n    self.adb.wait_for_device()\n  File \"/Users/gaoxiang/.local/share/virtualenvs/Pytest_Allure_Airtest_Demo-Nvoc_r-F/lib/python3.6/site-packages/airtest/core/android/adb.py\", line 300, in wait_for_device\n    raisefrom(DeviceConnectionError, \"device not ready\", e)\n  File \"/Users/gaoxiang/.local/share/virtualenvs/Pytest_Allure_Airtest_Demo-Nvoc_r-F/lib/python3.6/site-packages/airtest/utils/compat.py\", line 55, in raisefrom\n    raise_from(exc_type(message), exc)\n  File \"<string>\", line 3, in raise_from\n"}, "start": 1588639441838, "stop": 1588639476883}], "attachments": [{"name": "create app fail: 'device not ready'", "source": "700a565e-db5e-4d77-8620-79197d866ada-attachment.txt", "type": "text/plain"}], "start": 1588639441837, "stop": 1588639476894}], "start": 1588639441837, "stop": 1588639476896}], "start": 1588639441837, "stop": 1588639477429}